[metadata]
name = tkpixelfont
version = 0.1.0
author = Terry Greeniaus
author_email = terrygreeniaus@gmail.com
description = tkinter-based pixel font drawing tool.
long_description = file: README.rst
long_description_content_type = text/x-rst
keywords = pixel art font
url = https://github.com/tgree/tkpixelfont
license = License :: OSI Approved :: MIT License
classifiers =
    Operating System :: POSIX
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License

[options]
python_requires = >=3.6
packages =
    tkpixelfont

[options.entry_points]
console_scripts =
    tkpixelfont = tkpixelfont.tkpixelfont:_main
